/* Projet DIVE */
/* Script de création des tables */

ALTER 	TABLE CENTRE 			DROP CONSTRAINT FK_CENTRE_IDLIEU;
ALTER   TABLE LIEU        DROP CONSTRAINT LIVI_LIDEP;
DROP 	TABLE LIEU;
CREATE 	TABLE LIEU(
	IDLIEU	NUMERIC(3)		NOT NULL  PRIMARY KEY,
	LIVI	VARCHAR2(40)	NOT NULL,
	LIPA	VARCHAR2(40)	NOT NULL,
	LIDEP	VARCHAR2(3),
  CONSTRAINT LIVI_LIDEP UNIQUE(LIVI,LIDEP));

ALTER	TABLE ACCOMPAGNER 	DROP CONSTRAINT FK_ACCOMPAGNER_IDCENTRE;
DROP 	TABLE CENTRE;
CREATE 	TABLE CENTRE(
	IDCENTRE	NUMERIC(3)		NOT NULL	PRIMARY KEY,
	CNOM	VARCHAR2(75)	NOT NULL,
	IDLIEU	NUMERIC(3),
	CONSTRAINT FK_CENTRE_IDLIEU	FOREIGN KEY (IDLIEU) REFERENCES LIEU(IDLIEU));

ALTER	TABLE PLONGEE 		DROP CONSTRAINT FK_PLONGEE_IDSITE;
ALTER	TABLE ACCOMPAGNER 	DROP CONSTRAINT FK_ACCOMPAGNER_IDSITE;
ALTER TABLE SITE      DROP CONSTRAINT CK_SITE_SLAT;
ALTER TABLE SITE      DROP CONSTRAINT CK_SITE_SLONG;
DROP 	TABLE SITE;
CREATE 	TABLE SITE(
	IDSITE	NUMERIC(4)		NOT NULL	PRIMARY KEY,
	SNOM	VARCHAR2(50)	NOT NULL,
	SLAT	NUMBER(7,4),
	SLONG	NUMBER(7,4),
  CONSTRAINT CK_SITE_SLAT  CHECK  (SLAT>0),
  CONSTRAINT CK_SITE_SLONG CHECK (SLONG>0));

ALTER   TABLE ESPECE  DROP CONSTRAINT FK_ESPECE_FNOM;
DROP   TABLE FAMILLE;
CREATE  TABLE FAMILLE(
  FNOM  VARCHAR2(50)  NOT NULL PRIMARY KEY);

ALTER	TABLE OBSERVER		DROP CONSTRAINT FK_OBSERVER_ENOM;
DROP	TABLE ESPECE;
CREATE	TABLE ESPECE(
	ENOM	VARCHAR2(50)	NOT NULL	PRIMARY KEY,
	EURL	VARCHAR2(255),
  FNOM  VARCHAR2(50),
  CONSTRAINT FK_ESPECE_FNOM  FOREIGN KEY (FNOM)  REFERENCES FAMILLE(FNOM));

ALTER 	TABLE CLASSIFIER	DROP CONSTRAINT FK_CLASSIFIER_TNOM;
DROP	TABLE TYPEP;
CREATE	TABLE TYPEP(
	TNOM	VARCHAR2(30)	NOT NULL	PRIMARY KEY);

ALTER	TABLE PLONGER 		DROP CONSTRAINT FK_PLONGER_DNOM;
DROP	TABLE DECO;
CREATE	TABLE DECO(
	DNOM	VARCHAR2(20)	NOT NULL	PRIMARY KEY);

ALTER	TABLE PLONGER 		DROP CONSTRAINT FK_PLONGER_IDPLON;
ALTER	TABLE OBSERVER		DROP CONSTRAINT FK_OBSERVER_IDPLON;
ALTER	TABLE CLASSIFIER	DROP CONSTRAINT FK_CLASSIFIER_IDPLON;
ALTER	TABLE ACCOMPAGNER	DROP CONSTRAINT FK_ACCOMPAGNER_IDPLON;
ALTER	TABLE PARTAGER		DROP CONSTRAINT FK_PARTAGER_IDPLON;
DROP 	TABLE PLONGEE;
CREATE 	TABLE PLONGEE(
	IDPLON	NUMERIC(6)		NOT NULL	PRIMARY KEY,
	PDT		DATE			NOT NULL,
  	PHR   	VARCHAR2(5) 	NOT NULL, /* En Time */
	PTA		NUMBER(4,2),
	PTES	NUMBER(4,2),
	IDSITE	NUMERIC(4),
	CONSTRAINT FK_PLONGEE_IDSITE	FOREIGN KEY (IDSITE)	REFERENCES SITE(IDSITE));

ALTER	TABLE PLONGER		DROP CONSTRAINT FK_PLONGER_PMAIL;
ALTER	TABLE OBSERVER		DROP CONSTRAINT FK_OBSERVER_PMAIL;
ALTER	TABLE CLASSIFIER	DROP CONSTRAINT FK_CLASSIFIER_PMAIL;
ALTER	TABLE OBTENIR		DROP CONSTRAINT FK_OBTENIR_PMAIL;
ALTER	TABLE PARTAGER		DROP CONSTRAINT FK_PARTAGER_PMAIL;
ALTER TABLE PERSONNE    DROP CONSTRAINT CK_PERSONNE_PTEL;
DROP 	TABLE PERSONNE;
CREATE 	TABLE PERSONNE(
	PMAIL	VARCHAR2(50)	NOT NULL	PRIMARY KEY,
	PNOM	VARCHAR2(25)	NOT NULL,
	PPRE	VARCHAR2(25)	NOT NULL,
	PDTN	DATE,
	PTEL	NUMERIC(15),
  CONSTRAINT CK_PERSONNE_PTEL  CHECK (PTEL>0));

ALTER	TABLE PARTAGER		DROP CONSTRAINT FK_PARTAGER_RNOM;
DROP 	TABLE ROLE;
CREATE 	TABLE ROLE(
	RNOM	VARCHAR2(25)	NOT NULL	PRIMARY KEY);	

ALTER	TABLE OBTENIR		DROP CONSTRAINT FK_OBTENIR_CNOM;
DROP	TABLE CERTIFICATION;
CREATE 	TABLE CERTIFICATION(
	CNOM	VARCHAR2(60)	NOT NULL	PRIMARY KEY);
	
DROP 	TABLE ACCOMPAGNER;
CREATE 	TABLE ACCOMPAGNER(
	IDCENTRE	NUMERIC(3),
	IDSITE	NUMERIC(4),
	IDPLON	NUMERIC(6),
	CONSTRAINT FK_ACCOMPAGNER_IDCENTRE	FOREIGN KEY (IDCENTRE)	REFERENCES CENTRE(IDCENTRE),
	CONSTRAINT FK_ACCOMPAGNER_IDSITE	FOREIGN KEY (IDSITE)	REFERENCES SITE(IDSITE),
	CONSTRAINT FK_ACCOMPAGNER_IDPLON	FOREIGN KEY (IDPLON)	REFERENCES PLONGEE(IDPLON),
	CONSTRAINT PK_ACCOMPAGNER		PRIMARY KEY (IDCENTRE,IDSITE,IDPLON));

DROP	TABLE OBTENIR;
CREATE 	TABLE OBTENIR(
	PMAIL	VARCHAR2(50),
	CNOM	VARCHAR2(60),
	DTOBT	DATE,
	CONSTRAINT FK_OBTENIR_PMAIL	FOREIGN KEY (PMAIL)		REFERENCES PERSONNE(PMAIL),
	CONSTRAINT FK_OBTENIR_CNOM	FOREIGN KEY (CNOM)		REFERENCES CERTIFICATION(CNOM),
	CONSTRAINT PK_OBTENIR           PRIMARY KEY(PMAIL,CNOM));

ALTER	TABLE PLONGER DROP CONSTRAINT CK_PVISI;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PDIF;
ALTER	TABLE PLONGER DROP CONSTRAINT CK_PPO2;
ALTER	TABLE PLONGER DROP CONSTRAINT CK_PPHE;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PPRO;
ALTER	TABLE PLONGER DROP CONSTRAINT CK_PDUR;
ALTER	TABLE PLONGER DROP CONSTRAINT CK_PNUM;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PLES;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PCB;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PPD;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PPA;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL1P;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL2P;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL3P;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL1T;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL2T;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL3T;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL1O;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL2O;
ALTER 	TABLE PLONGER DROP CONSTRAINT CK_PAL3O;
ALTER	TABLE PLONGER DROP CONSTRAINT PMAIL_PNUM;
DROP 	TABLE PLONGER;
CREATE	TABLE PLONGER(
	PMAIL	VARCHAR2(50),
	PHS		VARCHAR2(6),	/* A remplacer avant MEP par un trunc timestamp : but HH:MN */
	PPRO	NUMBER(5,2)		NOT NULL,
	PDUR	NUMERIC(3)		NOT NULL,
	POBS	VARCHAR2(255),
	PNUM	NUMERIC(4)		NOT NULL,
	PAL1P	NUMERIC(2),
	PAL1T	NUMBER(5,2),	
	PAL1O	NUMBER(2),
	PAL2P	NUMERIC(2),
	PAL2T	NUMBER(5,2),	
	PAL2O	NUMBER(2),	
	PAL3P	NUMERIC(2),	
	PAL3T	NUMBER(5,2),	
	PAL3O	NUMBER(2),	
	PLES	NUMERIC(2),
	PPD	NUMERIC(3),
	PPA	NUMERIC(3),
	PCB	NUMERIC(2),
	PNOT	NUMERIC(1),
	PVISI	NUMERIC(1),
	PDIF	NUMERIC(1),
	PPO2	NUMBER(4,2),
	PPHE	NUMBER(4,2),
	PTEP	NUMBER(4,2),
	IDPLON	NUMERIC(6)		NOT NULL,
	DNOM	VARCHAR2(20),
	CONSTRAINT FK_PLONGER_PMAIL		FOREIGN KEY (PMAIL)		REFERENCES PERSONNE(PMAIL),	
	CONSTRAINT FK_PLONGER_IDPLON	FOREIGN KEY (IDPLON)	REFERENCES PLONGEE(IDPLON),
	CONSTRAINT FK_PLONGER_DNOM		FOREIGN KEY (DNOM)		REFERENCES DECO(DNOM),	
	CONSTRAINT PK_PLONGER			PRIMARY KEY(IDPLON,PMAIL));
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PVISI 	CHECK (PVISI >=0 	AND PVISI<=5);
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PDIF	CHECK (PDIF >=0 	AND PDIF<=5);
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PPO2	CHECK (PPO2 >=0		AND PPO2<=100);
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PPHE	CHECK (PPHE>=0 		AND PPHE<=100);
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PPRO 	CHECK (PPRO>=0);
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PDUR	CHECK (PDUR>=0);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PNUM	CHECK (PNUM>=1);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PLES	CHECK (PLES>=0);
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PCB	CHECK (PCB>=0 		AND PCB<=30);
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PPD	CHECK (PPHE>=0 		AND PPHE<=300);
ALTER	TABLE PLONGER ADD CONSTRAINT CK_PPA	CHECK (PPHE>=0 		AND PPHE<=300);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL1P	CHECK (PAL1P>=0 	AND PAL1P<=100);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL2P	CHECK (PAL2P>=0 	AND PAL2P<=100);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL3P	CHECK (PAL3P>=0 	AND PAL3P<=100);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL1T 	CHECK (PAL1T>=0);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL2T 	CHECK (PAL2T>=0);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL3T 	CHECK (PAL3T>=0);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL1O	CHECK (PAL1O>=0 	AND PAL1O<=100);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL2O	CHECK (PAL2O>=0 	AND PAL2O<=100);
ALTER 	TABLE PLONGER ADD CONSTRAINT CK_PAL3O	CHECK (PAL2O>=0 	AND PAL3O<=100);
ALTER 	TABLE PLONGER ADD CONSTRAINT PMAIL_PNUM UNIQUE (PMAIL,PNUM);

ALTER 	TABLE PARTAGER DROP CONSTRAINT CK_PPAL;
DROP	TABLE PARTAGER;
CREATE	TABLE PARTAGER(
	IDPLON	NUMERIC(6),
  	PPAL  	NUMERIC(2),
	PMAIL	VARCHAR2(50),
	RNOM	VARCHAR2(25),
	CONSTRAINT FK_PARTAGER_IDPLON	FOREIGN KEY(IDPLON)		REFERENCES	PLONGEE(IDPLON),
	CONSTRAINT FK_PARTAGER_PMAIL	FOREIGN KEY(PMAIL)		REFERENCES 	PERSONNE(PMAIL),
	CONSTRAINT FK_PARTAGER_RNOM	FOREIGN KEY(RNOM)		REFERENCES	ROLE(RNOM),
	CONSTRAINT PK_PARTAGER		PRIMARY KEY(IDPLON,PPAL,PMAIL));
ALTER 	TABLE PARTAGER CONSTRAINT CK_PPAL	CHECK PPAL>=1;
	
DROP 	TABLE OBSERVER;
CREATE	TABLE OBSERVER(
	IDPLON	NUMERIC(6)		NOT NULL,
	PMAIL	VARCHAR2(50)		NOT NULL,
	ENOM	VARCHAR2(50),
	CONSTRAINT FK_OBSERVER_IDPLON	FOREIGN KEY (IDPLON)	REFERENCES PLONGEE(IDPLON),
	CONSTRAINT FK_OBSERVER_PMAIL	FOREIGN KEY (PMAIL) 	REFERENCES PERSONNE(PMAIL),	
	CONSTRAINT FK_OBSERVER_ENOM	FOREIGN KEY (ENOM) 	REFERENCES ESPECE(ENOM),
	CONSTRAINT PK_OBSERVER		PRIMARY KEY (PMAIL,IDPLON,ENOM));

DROP	TABLE CLASSIFIER;
CREATE 	TABLE CLASSIFIER(
	IDPLON	NUMERIC(6)		NOT NULL,
	PMAIL	VARCHAR2(50)		NOT NULL,
	TNOM	VARCHAR2(30)		NOT NULL,
	CONSTRAINT FK_CLASSIFIER_IDPLON	FOREIGN KEY (IDPLON)	REFERENCES PLONGEE(IDPLON),
	CONSTRAINT FK_CLASSIFIER_PMAIL	FOREIGN KEY (PMAIL) 	REFERENCES PERSONNE(PMAIL),	
	CONSTRAINT FK_CLASSIFIER_TNOM	FOREIGN KEY (TNOM) 		REFERENCES TYPEP(TNOM),
	CONSTRAINT PK_CLASSIFIER		PRIMARY KEY (PMAIL,IDPLON,TNOM));