/* Script de création des séquences d'auto-incrémentation des index */
CREATE SEQUENCE Seq_Lieu
  INCREMENT BY 1 START WITH 1 MAXVALUE 999;

CREATE SEQUENCE Seq_Centre
  INCREMENT BY 1 START WITH 1 MAXVALUE 999;
  
CREATE SEQUENCE Seq_Site
  INCREMENT BY 1 START WITH 1 MAXVALUE 9999;  

CREATE SEQUENCE Seq_Plongee
  INCREMENT BY 1 START WITH 1 MAXVALUE 999999;