CREATE OR REPLACE TRIGGER AUP_PERSONNE
AFTER UPDATE ON PERSONNE
FOR EACH ROW

BEGIN

  UPDATE PLONGER
  SET PMAIL = :new.PMAIL
  WHERE PLONGER.PMAIL=:old.PMAIL;

  UPDATE CLASSIFIER
  SET PMAIL = :new.PMAIL
  WHERE CLASSIFIER.PMAIL=:old.PMAIL;

  UPDATE PARTAGER
  SET PMAIL = :new.PMAIL
  WHERE PARTAGER.PMAIL=:old.PMAIL;

  UPDATE OBSERVER
  SET PMAIL = :new.PMAIL
  WHERE OBSERVER.PMAIL=:old.PMAIL;

END;