create or replace TRIGGER BDE_PLONGEE
BEFORE DELETE ON PLONGEE
FOR EACH ROW

BEGIN

  DELETE FROM PARTAGER
  WHERE PARTAGER.IDPLON=:old.IDPLON;
  
  DELETE FROM OBSERVER
  WHERE OBSERVER.IDPLON=:old.IDPLON;
  
  DELETE FROM CLASSIFIER
  WHERE CLASSIFIER.IDPLON=:old.IDPLON;
  
  DELETE FROM ACCOMPAGNER
  WHERE ACCOMPAGNER.IDPLON=:old.IDPLON; 
  
  DELETE FROM PLONGER
  WHERE PLONGER.IDPLON=:old.IDPLON;

END;