create or replace TRIGGER BDE_PLONGER
BEFORE DELETE ON PLONGER
FOR EACH ROW

BEGIN

  DELETE FROM PARTAGER
  WHERE PARTAGER.IDPLON=:old.IDPLON AND PMAIL=:old.PMAIL;
  
  DELETE FROM OBSERVER
  WHERE OBSERVER.IDPLON=:old.IDPLON AND PMAIL=:old.PMAIL;
  
  DELETE FROM CLASSIFIER
  WHERE CLASSIFIER.IDPLON=:old.IDPLON AND PMAIL=:old.PMAIL;
  
END;